### PR TITLE
hotfix: center text horizontally in button

### PR DESCRIPTION
**Pull request by nathanfranklin**
## Overview

This centers the text horizontally in the c-button.

## Related

This was noticed in https://github.com/TACC-Cloud/hazmapper/pull/208#discussion_r1492996930

## Testing

See instructions here: https://github.com/TACC/Core-Styles/pull/307#issuecomment-1949496991
…

## UI

See screenshots here:  https://github.com/TACC/Core-Styles/pull/307#issuecomment-1949496991

### CODE REVIEW

**Comment by wesleyboar** [comment]
I am too excited about a PR to wait for Monday.

The UI demo doesn't do a very good job revealing this fix — hence the bug release — so I've done my best to show it (below). Also, reminder, you can test this on client even while PR is open by installing it via branch (`npm install --save-dev @tacc/core-styles@hotfix/center-button-text`).

0. (`npm ci`)
1. `npm run watch`
2. `npm run start`
3. Open http://localhost:3000/components/detail/c-button--secondary.
4. Verify all button text is centered.

| Before | After |
| - | - |
| before | after |

**Comment by nathanfranklin** [comment]
> npm install --save-dev @tacc/core-styles@hotfix/center-button-text

npm install --save-dev tacc/core-styles#hotfix/center-button-text

I used that and also checked on the hazmapper branch that things look correct (did a repo wide replace of `@tacc/core-styles/dist/` with `@tacc/core-styles/src/lib` to see the change on hazmapper)

**Comment by nathanfranklin** [comment]
When do you update the `dist`.  Is that the PR authors responsibility to update that or is that done when making a release?

**Comment by wesleyboar** [comment]
@nathanfranklin Unfortunately, for now, author must update `dist`.

> replace of `@tacc/core-styles/dist/` with `@tacc/core-styles/src/lib`

Hmm, I see why. After you commit `dist/`, I suggest using `dist/`, because client projects may not support all the same PostCSS plugins for the `src/` as Core-Styles (though Vite seems to just work most of the time). _I welcome feedback and brainstorming._

<details>

One day, `dist/` will be updated automatically on publish. But, then how will users test `dist/` off a branch? Perhaps author can commit just it in `dist/`, for testing, then delete it, before merge.

</details>

**Review by wesleyboar — APPROVED** [review]
Thanks!

**Pull request merged**
